[project]
name = "mess-bot"
version = "1.0.0"
description = "Mess Menu Bot for Telegram"
requires-python = ">=3.10"

[tool.poetry.dependencies]
python-telegram-bot = "^20.7"
pytz = "^2024.1"
psutil = "^5.9.8"
requests = "^2.31.0" 